Vagrant.configure("2") do |config|
  config.vm.hostname = "myWindows2012r2"
  config.vm.box = "kensykora/windows_2012_r2_standard"
  #config.omnibus.chef_version = :latest
  #config.vm.network :private_network, ip: "33.33.33.10"
  #config.vm.boot_timeout = 120
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "/Users/thuynguyen/ws/chef-repo/cookbooks/trace3/Berksfile" 

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = [ '/Users/thuynguyen/ws/chef-repo/cookbooks', '/Users/thuynguyen/ws/chef-repo/cookbooks_from_Berkshelf' ]
    chef.run_list = [
     "recipe[trace3::default]"
    ]
  end
end
