---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows_2012_r2
    driver:
      box: kensykora/windows_2012_r2_standard

suites:
  - name: default
    run_list:
      - recipe[trace3::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
